# Generated by Django 6.0.1 on 2026-02-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(verbose_name=127)),
                ('texto', models.TextField()),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
