# Generated by Django 6.0.1 on 2026-02-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='date',
            new_name='data',
        ),
    ]
